<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

use AppVvp\General\FileSystem;
use AppVvp\Pages\Page;

/**
 *
 */
?>
<div class="borderOuter" style="width: 60.0%;">
  <div class="borderInner" style="text-align: center;">
	<h3>!! ERASE !! <?php echo hh($this->getFileDescr()); ?></h3>
	<form method="POST" action="<?php echo 
			uu( SAFE_RU_CURR_PAGE_URL . QSDLM1 . 'nqa=&ftyp=' . ur($this->getFileType()) ); ?>">
		<input type="submit" id="SUBMIT1" name="SUBMIT1" value="!! ERASE !!">

		<span style="font-size: 1.2em;">&nbsp;&nbsp;</span>

		<input type="button" value="Exit" 
			onclick="window.location.replace('<?php echo 
					uu(FilNams::getPgUrl($_SESSION[Page::SV_ADMINPAG])); ?>');">
		<div class="divspc01_5"></div>
	</form>
  </div>
</div>
<?php
//if (substr($this->getFileType(), 0, 1) === 'D') {
if ($this->getFileType()[0] === 'D') { // Files in a directory
	FileSystem::chkDirFileCnt($this->getFileName());
	if ($this->getErase()) {
		FileSystem::eraseDir($this->getFileName(), $this->getFileType());
	}
} else { // Single separate file
	$REC_CNT1 = FileSystem::chkFileRecCnt($this->getFileName());
	if ($this->getErase()) {
		FileSystem::eraseFile($this->getFileName(), $REC_CNT1);
	}
}
?>
