<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

use AppVvp\Db\DbAccess;

/**
 * Content for DISPLAY USERS page
 */
?>
<div class="borderOuter" style="width: 60.0%;">
  <div class="borderInner" style="text-align: center;">
	<h3>Display Users</h3>
  </div>
</div>

<br>
<table class="cntr_wd98pct">
    <tr>
        <th>User</th>
        <th>Cust#</th>
        <th>Admin</th>
        <!--<th>Password</th>-->
        <th>Dir Name</th>
        <th>PW Reset Token</th>
        <th>PW Reset Time</th>
        <th>SQL Timestamp</th>
    </tr>
<?php
$res = DbAccess::getUsers();
foreach ($res as $SQL_ROW => $SQL_COLS_ARY):
	echo '<tr>', "\n";
	foreach ($SQL_COLS_ARY as $COL => $VAL):
		if ($COL !== 'password') {
			echo '<td>[', hh($VAL), ']</td>', "\n";
		}
	endforeach;
	echo '</tr>', "\n";
endforeach;
?>
</table>
