<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

use AppVvp\General\SysMain;

/**
 *
 */

$_filter = $this->getFilter();
$_ignore = array();
// ========================================================
if ($_filter) {
  $_ignore["localhost"] = "localhost";
  $_ignore["127.0.0.1"] = "127.0.0.1";
//$_ignore["user207x11.lacoe.edu"] = "SB's PC @ work";   //2007(?)

  $_ignore["cpe-76-91-194-19.socal.res.rr.com"] = "our cable host name - 2014-11"; // 2014-11-12 ?? - hosting IP addr change
  $_ignore["76.91.194.19"] = "our cable host name - 2014-11"; // 2014-11-12 ?? - hosting IP addr change
  $_ignore["cpe-76-171-168-180.socal.res.rr.com"] = "our cable host name - 2014-04"; // 2014-04-11
  $_ignore["76.171.168.180"] = "our cable host name - 2014-04"; // 2014-04-11 - they switched to IP addr
//$_ignore["cpe-76-166-120-37.socal.res.rr.com"] = "our cable host name"; // 2008(?)

//$_ignore["Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"] = "Google crawler";
//$_ignore["Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)"] = "Yahoo! spider";
//$_ignore["msnbot/1.0 (+http://search.msn.com/msnbot.htm)"] = "MSN livebot-###-###-###-###.search.live.com";
}
// ========================================================


function report_line($rptdata1, $dlm1)
{
	echo "<br />" , 
		//Change order of display items here:
		//sprintf("%04d", $ii) , " " , 
		$rptdata1[0] , $dlm1 , //timestamp
		$rptdata1[1] , $dlm1 , //client hostname
		$rptdata1[2] , $dlm1 , //client IP addr
		'SID: ' , $rptdata1[7] , $dlm1 , //session-id
		$rptdata1[4] , $dlm1 , //client OS
		$rptdata1[5] , $dlm1 , //client browser
		$rptdata1[3] , $dlm1 , //page name/display
		$rptdata1[6] , $dlm1 , //HTTP_USER_AGENT
		"\n";
}

function xecho($lvl, $parm1)
{
	$spaces = 
		"                                                                              ";
	echo substr($spaces, 0, ($lvl * 3)) , $parm1;
}

$dlm = SysMain::LOGFILE_DLM;
$_recsz = 512;
$_filtered = array();
$_logfile = FilNams::getLogFileFnam();

if (array_key_exists('SERVER_ADDR', $_SERVER)) {
	$_server_ip_addr = $_SERVER['SERVER_ADDR'];
} else {
	$_server_ip_addr = "(no server IP addr)";
}
$_client_remote_hostnam = gethostbyaddr($_SERVER['REMOTE_ADDR']); //also use $_SERVER['REMOTE_HOST']

$dteprv = "0000-00-00";

// ===================================================================
// ===================== START OF HTML CONTENT =======================
// ===================================================================
echo '<div>';

if ($_filter)
	echo "*WARNING* Filter is ON ...<br />\n";
else
	echo "Filter is OFF ...<br />\n";

echo "<h3>", date("Y-m-d - h:i a"), ' - Site Access Logfile Listing</h3>';
echo '<div style="width: 300%" class="text1">';

echo '<a href="', uu( FilNams::getPgUrl(FilNams::PN_ERASEFILE) . QSDLM1 . 'ftyp=L' ), 
		'">!! ERASE !! Site Access Logfile</a><br /><br />', "\n";

echo '<br />';
if (!is_file($_logfile)) {
	echo
		"<br /><strong>*******************************************************" , 
		"<br />* ERROR: Invalid filename ref '$_logfile' -OR- does not exist." , 
		"<br />*******************************************************</strong>";
	exit();
}
echo "<strong>Client hostname/ip address: $_client_remote_hostnam - ", $_SERVER['REMOTE_ADDR'];
echo "<br />&nbsp;&nbsp;&nbsp;&nbsp;Server name/ip address: " , RAW_SERVER_NAME , " - $_server_ip_addr\n";
echo "<br />===================================================\n";
echo "</strong>\n";
$cnt1 = 0;
echo "<br />Reading logfile ...\n";
$fh = fopen($_logfile, 'r');
while (!feof($fh)) {
	$cnt1++;
	$data[$cnt1] = trim(fgets($fh, $_recsz));
}
echo " Closing logfile ...\n";
fclose($fh);

for ($ii = $cnt1 - 1; $ii > 0; $ii--) {
	$ok = true;
	$output1[$ii] = explode($dlm, $data[$ii]);
	if ($_filter) {
		$colCnt = count($output1[$ii]);
		if ($colCnt < 7) {
			echo
				"<br /><strong>*******************************************************" , 
				"<br />* ERROR: Invalid record format (missing or wrong # of delimiters):" , 
				"<br />$data[$ii]" , 
				"<br />* ABORTED ..." , 
				"<br />*******************************************************</strong>";
			break;
		} elseif ($colCnt == 7) {  // add blank item to account for older rec-layout
			$output1[$ii][7] = '';
		}
		if (array_key_exists($output1[$ii][1], $_ignore)) { // remote hostname
			$ok = false;
		} elseif (array_key_exists($output1[$ii][2], $_ignore)) { // client IP addr
			$ok = false;
		} elseif (array_key_exists($output1[$ii][6], $_ignore)) { // HTTP_USER_AGENT
			$ok = false;
		} else {
			$tmp2 = explode('.', $output1[$ii][1]);
			if (count($tmp2) > 1) { //2nd piece of remote hostname
				if (array_key_exists($tmp2[1], $_ignore)) {
					$ok = false;
				}
			}
		}
	}
	if ($ok) {
		$dtecur = substr($data[$ii], 0, 10);
		if ($dtecur != $dteprv) {
			$dteprv = $dtecur;
			echo "<br />\n";
		}
		report_line($output1[$ii], $dlm);
	} else {
		$_filtered[] = $output1[$ii];
	}
}
echo "<br />===========================================================================\n";
if ($_filter)
{
	echo "<br /><br /><strong>The following filter-keys are defined:</strong>\n";
	for ($ii = 0; $ii < count($_ignore); $ii++)
	{
		echo "<br />" , current($_ignore) ,  " $dlm " , key($_ignore) , "\n";
		next($_ignore);
	}
	echo "<br /><br />===========================================================================\n";
	echo "<br /><strong>The following records were filtered out:</strong>\n";
	$dteprv = "0000-00-00";
	for ($ii = 0; $ii < count($_filtered); $ii++)
	{
		$dtecur = substr($_filtered[$ii][0], 0, 10);
		if ($dtecur != $dteprv) 	{$dteprv = $dtecur;		echo "<br />\n";}
		//echo "<br />" , current($_filtered) ,  " $dlm " , key($_filtered) , "\n";
		//next($_filtered);
		report_line($_filtered[$ii], $dlm);
	}
}
echo "<br />===========================================================================\n";

xecho(1, "</div>\n");
echo "</div>\n";
