<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

/**
 * Content for PHP INFO page
 */
?>
<div class="borderOuter" style="width: 70.0%;">
    <div class="borderInner" style="text-align: center;">
	    <!-- ===== direct phpinfo() output to iframe container ===== -->
        <iframe style="border: none; width: 100.0%; height: 48.0em;" 
		    src="<?php echo uu(SAFE_RU_CURR_PAGE_URL), QSDLM1, 'phpinfo=1'; ?>">
        </iframe>
    </div>
</div>
