<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

/**
 * Content for PW HASH page
 */

function check_password($pw, $hashed_pw)
{
	if (password_verify($pw, $hashed_pw)) {
		echo 'VERIFY of PW vs HASH is CORRECT: [', $pw, ']<br />';
	} else {
		echo 'ERROR !!!! PASSWORD DOES NOT VERIFY AGAINST HASHED VALUE !!!!<br />';
	}
}

if (strtoupper($_SERVER['REQUEST_METHOD']) !== 'POST') {
//	$pw = 'We Have 2 Many O[ptions In Lif]e';
	$pw = '123434';
	$hash_test = '';
} else {
	$pw		   = $_POST['pw'];
	$hash_test = $_POST['hash_test'];
}

if (empty($hash_test)) {
	$hashed_pw = password_hash($pw, PASSWORD_BCRYPT);
} else {
	$hashed_pw = $hash_test;
}
?>
<div class="borderOuter" style="width: 60.0%;">
  <div class="borderInner" style="text-align: center;">
	<h3>PW Hash/Check - BCRYPT password_hash() / password_verify()</h3>
	<table>
		<tr><td>
			<?php
			//TEST: force check_password() failure:
			//$hashed_pw = '\$2a\$08\$VuMz4qphITb9uA/6tsWJnuHYII7r9H9JpN37cgRq40RVakdP9kYhi';
			echo '';
			echo "length of pw: " . strlen($pw) . "<br />";
			echo "length of hash: " . strlen($hashed_pw) . "<br />";
			echo "<br />";
			//================
			check_password($pw, $hashed_pw);
			//================
			echo "<br />";
			?>
			<form method="POST" action="<?php echo uu(SAFE_RU_CURR_PAGE_URL); ?>">
				<table>
					<tr>
						<td>ENTER PW:</td>
						<td><input type="text" name="pw" id="pw" value="<?php echo $pw; ?>" 
								   size=50></td>
					</tr>
					<tr>
						<td>HASHED-pw:</td>
						<td><input type="text" name="hashed_pw" id="hashed_pw" value="<?php echo 
								$hashed_pw; ?>" size=70></td>
					</tr>
					<tr>
						<td>HASH-test - ENTER VALUE:</td>
						<td><input type="text" name="hash_test" id="hash_test" value="<?php echo 
								$hash_test; ?>" size=70></td>
					</tr>
				</table>
				<p><input type="submit" value="Submit"></p>
			</form>
		</td></tr>
	</table>
  </div>
</div>
