<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

use AppVvp\Validators\Validator;

/**
 * Content for setting custom session vars
 */

setSessVarOptions();
?>
<div class="borderOuter" style="width: 60.0%;">
  <div class="borderInner" style="text-align: center;">
	<h3>Set Session Variables</h3>

	<br />
	<a href="<?php echo uu(FilNams::getPgUrl(FilNams::PN_ERASEFILE) . QSDLM1 . 'ftyp=DS'); ?>">
            !! DELETE !! SESSION ID FILES (clean-up)</a><br /><br />

    <span>----------------------------------------------------------------</span><br /><br />

	<span>CFV: [<?php echo CFV_CURR; ?>]</span> | 
    <a href="<?php echo uu( FilNams::getPgUrl(FilNams::PN_SETSESSVARSP) . QSDLM1 . 
				Validator::SV_CFV_METHOD . '=' . ur(CFV_VAL1) ), '">', 
					CFV_VAL1; ?></a> | 
    <a href="<?php echo uu( FilNams::getPgUrl(FilNams::PN_SETSESSVARSP) . QSDLM1 . 
				Validator::SV_CFV_METHOD . '=' . ur(CFV_VAL2) ), '">', 
					CFV_VAL2; ?></a><br /><br />

    <span>----------------------------------------------------------------</span><br /><br />

    <span>ENFORCE PASSWORD RULES: [<?php echo PSWR_CURR_DSP; ?>] | </span>
    <a href="<?php echo uu( FilNams::getPgUrl(FilNams::PN_SETSESSVARSP) . QSDLM1 . 
				Validator::SV_ENFORCE_PW_RULES . '=' . ur(PSWR_NEW) ), '">', 
					PSWR_NEW_DSP; ?></a><br /><br />

  </div>
</div>
