<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

use AppVvp\General\PgLinkFactory;
use AppVvp\General\SysMain;

/**
 * Check if JavaScript disabled
 */

// ===================================================================
if (!isset($_SESSION[SysMain::SV_JS_DISABLED]) && 
			!PgLinkFactory::isCurrentPage(FilNams::PN_ERRMSG)): ?>
<noscript>
    <?php	// ---------------------------------------------------------
			// --- If <noscript> is triggered (JS disabled), then reload page w/ 
			//     parm JSdisabled=1: ?>
    <meta http-equiv="refresh" content="0; url=<?php 
			echo uu( SAFE_RU_CURR_PAGE_URL . '?' . SysMain::SV_JS_DISABLED . '=1' ); ?>">
</noscript>
<?php endif; ?>
<?php if (isset($_SESSION[SysMain::SV_JS_DISABLED])): 
			// ---------------------------------------------------------
			// --- JS was flagged as disabled on prior request: attempt to exec the
			//     following JS code; if it fires, then JS is now enabled: reload 
			//     page w/ parm JSdisabled=0.  Use split on '?' to remove any 
			//     prior parms [takes only 1st element of array]:: ?>
<script>
	alert(	'***************************************************\n\n' + 
			'JavaScript is now enabled in your browser\n\n' + 
			'***************************************************');
	window.location.replace(window.location.href.split('?')[0] + '?<?php echo 
			SysMain::SV_JS_DISABLED; ?>=0');
</script>
<?php endif; // ============================================================
