<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

/**
 * JavaScript footer for stillframes page
 */
?>
<script src="<?php echo hh(FilNams::getRelPathJs()); ?>/libs/jquery.min.js"></script>
<script src="<?php echo hh(FilNams::getRelPathJs()); ?>/json-common.js"></script>
<script>
<?php
App::$page->renderJson();
?>
</script>
<script src="<?php echo hh(FilNams::getRelPathJs()); ?>/stillframes.js"></script>
