<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

use AppVvp\Forms\Form;
use AppVvp\General\BusDefs;
use AppVvp\General\SysMain;
use AppVvp\Pages\Page;
use AppVvp\Validators\Validator;

/**
 * Content for New User page
 */
?>
<div id="mainOuterBorder1" class="borderOuter">
    <div class="borderInner">
        <h2>
            Register with <?php echo BusDefs::BUSNAME1_F2; ?>
        </h2>
        <p style="text-align: center;">
            <strong>You must create a login username to access and upload your videos.<br><br>
				Please enter a NEW USERNAME and PASSWORD:</strong>
        </p>
		<?php App::$page->getForm1()->renderPwRules1(Page::INDENT_2); ?>
        <form class="pagForm" id="<?php echo hh(App::$page->getForm1()->getFormName()); ?>" name="<?php 
				echo hh(App::$page->getForm1()->getFormName()); ?>" 
				method="POST" action="<?php echo uu(SAFE_RU_CURR_PAGE_URL); ?>">
			<?php App::$page->getForm1()->renderHiddenFfos1(Page::INDENT_4); ?>
            <table class="cntr_wd98pct">
                <tr>
                    <td class="formFldDescr">
                        <span class="alertColor">*required field</span>
                    </td>
                </tr>
				<?php App::$page->getForm1()->renderFfos1(Page::INDENT_4); ?>
            </table>
            <div class="btnRow1">
                <input class="btnForm" type="submit" id="<?php echo 
					Form::FBN_SUBMIT; ?>" name="<?php 
					echo Form::FBN_SUBMIT; ?>" value="CONTINUE">
			<?php echo "\n"; if (Validator::isCfvMethod(Validator::CFV_JS) && 
						!isset($_SESSION[SysMain::SV_JS_DISABLED])): ?>
                <input class="btnForm" id="btnFormClearChgs" type="button" value="Clear (discard)">
			<?php endif; ?>
			<?php echo "\n"; if (SysMain::getBrowser() != SysMain::BROWSER_MSIE): ?>
                <input class="btnForm" type="submit" form="FormReload" id="btnFormReload" value="Reload page">
			<?php endif; ?>

            </div>
        </form>
	<?php echo "\n"; if (SysMain::getBrowser() != SysMain::BROWSER_MSIE):
		// For html5 form="FormReload" attrib - will work even is JS is disabled: ?>
        <form id="FormReload" action="<?php echo uu(SAFE_RU_CURR_PAGE_URL); ?>">
        </form>
	<?php endif; ?>

    </div>
</div>
