<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

use AppVvp\General\BusDefs;
use AppVvp\Pages\Page;

/**
 * Content for 'Contact us' page
 */
?>
<div id="mainOuterBorder1" class="borderOuter">
  <div id="contactUs" class="borderInner">
    <h2>Contact Us:</h2>
    <h3><?php echo BusDefs::BUSNAME1_F1; ?>&nbsp;-&nbsp;&nbsp;<a class="linkNormalWeb" 
        href="http://<?php echo BusDefs::WEBNAME1_F1; ?>/"><?php echo BusDefs::WEBNAME1_F2; ?></a></h3>
    <h3>Los Angeles Wedding and Special Event Videography</h3>
    <p class="pContactUs">
        <span class="contactUsNormal">Email: &nbsp;</span><a class="linkNormalWeb" 
                href="mailto:<?php echo 
						BusDefs::getMailTo1(); // already obfuscated; do not escape ?>">
        <?php echo BusDefs::EMAIL1_F1; ?></a>
    </p>
    <p class="pContactUs">
        <span class="contactUsNormal">Phone: &nbsp;</span><?php echo BusDefs::PHONE1_F1; ?>
        &nbsp;&nbsp;-&nbsp;&nbsp;
        <span class="contactUsNormal">Cell Phone: &nbsp;</span>310.650.4472
    </p>
    <p class="pContactUs">
        <span class="contactUsNormal">Contact: </span><?php echo BusDefs::CONTACT1_FIRSTNAME; ?> 
        <?php echo BusDefs::CONTACT1_LASTNAME; ?>
    </p>
    <p class="txtNotice1">
        All information provided is strictly confidential.&nbsp;&nbsp;It will not be 
        sold or given to anyone.
    </p>
  </div>
</div>

<?php
/* ===========================================================================
================================= LINKS ======================================
============================================================================== */
?>
<div id="mainOuterBorder2" class="borderOuter">
  <div class="borderInner" style="padding: 0.5em;">

    <h2>
		Other Wedding and Special Event Services:</h2>

    <?php // ==============================================================================; ?>
    <div style="text-align: center; border-bottom: 1px solid <?php 
			echo Page::DIVBORDR_COLR1B; ?>;">
        <p><a href="http://www.wedalert.com" target="_blank">
        <img src="http://www.wedalert.com/images/WedAlert/banners/WedAlert_white200x75.gif" 
			 border="0" height="65" alt="Your Wedding Planning Just Got Easier!"></a></p>

		<p><A HREF="http://www.at-la.com" target="_blank"><IMG SRC="http://www.at-la.com/@la.gif" 
		   ALT="@LA: The Guide to Greater Los Angeles and Southern California" BORDER=0></A></p>

		<p><a href="http://www.theweddingspot.com/ca/losangeles/" target="_blank">
			<img TITLE="Los Angeles Wedding Videography" ALT="Los Angeles Wedding Videography" 
			src="http://www.theweddingspot.com/images/tws_proudly_listed_com.jpg"></a></p>

        <p><a href="http://www.weddingsearches.com" target="_blank">
        <img src="http://www.weddingsearches.com/images/ws_ban_sm.gif" 
            alt="Wedding Searches - Your Wedding Search Engine" border=0></a></p>
		<p>
			<A href="http://www.weddinglenox.com"><IMG alt=WeddingLenox hspace=0 
			src="http://www.weddinglenox.com/newsletter/weblogo.jpg" align=baseline 
			border=0></A><BR><A href="http://www.weddinglenox.com">WeddingLenox</A>&nbsp;- 
			Wedding planning directory inlcuding&nbsp;the best wedding photographers, DJs, 
			planners,&nbsp;wedding videographers, makeup specialist, hairstyle 
			specialist,&nbsp;wedding decorators, florists, musicians, caterers and planning 
			services all in one place.</p>
    </div>
    <?php // =============================================================================; ?>
    <div id="textLinks" style="padding: 1.0em 0 1.0em 0;">
        <p>Member of Onewed.com - <a href="http://www.onewed.com/" target="_blank">Wedding</a> planning guide, and <a href="http://www.onewed.com/articles/articles_FL.html">wedding flowers</a></p>

        <p><?php echo BusDefs::BUSNAME1_F1; ?> is a premiere videographer in the <a href="http://www.videographies.com/page/videographers/b.507.g.4246.html">Los Angeles, California Videographers</a> community on Videographies.com.</p>

        <p><strong><a href="http://www.weddinggazette.com/" target="_blank">Wedding Gazette</a></strong><br />Transform your wedding inspirations into reality with helpful articles on wedding flowers, bridal showers, wedding favors, making a budget, dealing with Mom, and more. Free newsletter contains wedding trends, tips, shopping, and advice.</p>

        <p><strong><a href="http://www.bridecouture.com" target="_blank">Designer Wedding 
        Dress</a></strong><br />
        Bride Couture&trade; offers a secure online shopping experience for high end 
        designer bridal gowns. Up to 75% off retail prices. Unsurpassed quality 
        and detail. Vera Wang, Reem Acra, Amsale and many more!</p>

        <p><strong><a href="http://www.bouncecheap.com/" target="_blank">National Party Rental Network</a></strong> National Party Rental Network</p>

        <p><strong><a href="http://www.weddingmanor.com" target="_blank">
        Wedding Manor</a></strong><br />Your source for Wedding Professionals!</p>

        <p><strong><a href="http://www.weddingmuseum.com" target="_blank">Plan, book, rate your wedding at WeddingMuseum.com</a></strong></p>

        <p><strong><a href="http://ca.topweddingsites.com" target="_blank">Click here for wedding ideas from California Top Wedding Sites&trade;</a></strong></p>

        <p><a href="http://www.the-wedding-planner.com/" target="_blank">The-Wedding-Planner.com</a><br />
        Wedding planning resource with a national and international wedding vendor directory, expert articles, step-by-step planning, classified ads,
        and much more. It's never too soon to start planning!</p>

        <p><strong><a href="http://www.bestweddingsites.com" target="_blank">Best Wedding Sites</a></strong><br />
        The best online guide for wedding and honeymoon planning, accessories, favors, gift registries, invitations, shopping, local vendors and more.</p>

        <p><a href="http://www.wednet.com" target="_blank">Wedding planning and wedding vendors directory</a></p>

        <p><a href="http://www.americanbridal.com" target="_blank">Unique Wedding Favors</a> - We specialize in discount wedding favors, wedding party favors 
        and wedding gifts. We have elegant bridesmaids gifts, and unique groomsmen gifts for your wedding party and favor ideas.</p>

        <p>Featured Vendor in the <a href="http://www.LosAngelesWeddingList.com/wedding_videographers.php" target="_blank">Los Angeles Wedding Videographers Directory</a> at LosAngelesWeddingList.com</p>

        <p><a href="http://www.weddingcram.com" target="_blank" alt="Wedding Cram">Wedding Cram</a></p>

        <p><strong>SearchBridal.com</strong> -  <a href="http://www.searchbridal.com/" target="_blank">A bridal web directory</a> that offering all things about wedding website.</p>

        <p><strong>IWeddingDirectory.com</strong> - A guide and resources <a href="http://www.iweddingdirectory.com" target="_blank">wedding web directory</a></p>

        <br />
        <p><strong>DirectoryLocal.com</strong> - <a href="http://www.directorylocal.com" target="_blank">The United State directory </a> provides related useful resource, business information in United State.</p>

        <p><strong>BizCalifornia.com</strong> - <a href="http://www.bizcalifornia.com" target="_blank"> California business directory</a> provides related information to California.</p>

        <p><strong>DirectoryCalifornia.com </strong>- <a href="http://www.directorycalifornia.com" target="_blank">California directory</a> offers a vast selection for finding information and services with local business sites.</p>
        <br />

        <p><strong>WebWD.com</strong> - A <a href="http://www.webwd.com/" target="_blank">wedding directory</a> that guide to wedding, and wedding services, for your perfect wedding day.</p>

        <p><a href="http://www.top100site.net/in.php?id=kriskris" target="_blank">Visit top100site.net</a></p>

        <p><strong>ClickBridal.com</strong> - Comprehensive <a href="http://www.clickbridal.com" target="_blank">Wedding Web Directory</a></p>

        <p><a href="http://weddings-hq.com" target="_blank">Weddings HQ</a> Everything Wedding, from Wedding Advice to Weddings.</p>

        <p><A HREF="http://www.wedj.com" target="_blank" TITLE="Find a DJ or Photographer for you wedding or special event">Find a DJ for your wedding or special event</a></p>

        <?php /* --- Our link ---
        <p><a href="http://<?php echo BusDefs::WEBNAME1_F1; ?>/" target="_blank"><?php echo BusDefs::BUSNAME1_F1; ?></a> - 
        We will create a lovely, heart touching video of your once-in-a-lifetime event. 
        We offer high-quality, affordable videography services in Greater Los Angeles.<p>
         */; ?>
    </div>
  </div>
</div>
