<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

use AppVvp\Pages\Page;
use AppVvp\Pages\VideoPage;

/**
 * Content for VIDEO/WELCOME pages
 */

?>

<main id="vvpWelcome" role="main">
    <article role="article">
	<?php
    if (App::$page->isVideoPlayPage()) {
		// =====================================================================
		// =============== PLAY-VIDEO PAGE: EMBEDDED VIDEO OBJECT ==============
		// =====================================================================
		require FilNams::DN_TEMPLATES . FilNams::DS . 
				FilNams::DN_PAGES . FilNams::DS . 'videos-play' . '.' . TMPL_FILEEXT;
	} else {
		// ==========================================================
		// ================= 'WELCOME' PARAGRAPH ====================
		// ==========================================================
		require FilNams::DN_TEMPLATES . FilNams::DS . 
				FilNams::DN_PAGES . FilNams::DS . 'videos-welcome' . '.' . TMPL_FILEEXT;
    }
	?>
	<?php echo "\n";
	if ($_SESSION[VideoPage::SV_LOCAL_VIDEO] == "y") {
        echo '<p class="vidLocOrWebMsg">', 
				'<strong>[ *W* REFERENCING LOCAL VIDEO FILES ]</strong></p>';
	}
	if ($_SESSION[VideoPage::SV_LOCAL_VIDEO] == "n") {
        echo '<p class="vidLocOrWebMsg">', 
                '<strong>[ *W* REFERENCING INTERNET VIDEO FILES ]</strong></p>';
	} ?>
    </article>
</main>

<section id="videoLinks">
    <table id="vidTbl" class="vidLnksTbl">
		<?php
		// =====================================================================
		// ================= SAMPLE-VIDEO THUMBNAIL LINKS ======================
		// =====================================================================
		App::$page->renderVideoTnLinks(Page::INDENT_2); ?>
    </table>
</section>
