<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

use AppVvp\Forms\Form;
use AppVvp\General\PgLinkFactory;
use AppVvp\General\SysMain;
use AppVvp\Pages\Page;
use AppVvp\Pages\VideoPage;

/**
 * Public page template - common code for VIDEO/WELCOME pages
 * =============== PLAY-VIDEO PAGE ==============
 */

echo "\n";
if (App::$page->getVidFormat() === 'html5'): // ======= USE HTML5 ======= ?>
        <video width="<?php echo hh(App::$page->getVidWd()); ?>" <?php echo 
						hh(App::$page->getVidAutoplay()); ?> controls>
            <source src="<?php echo hh(App::$page->getVidSrc()); ?>.mp4" 
                    type='video/mp4; codecs="avc1.4D401E, mp4a.40.2"' />
            <source src="<?php echo hh(App::$page->getVidSrc()); ?>.webm" type="video/webm" />
            No video with a supported format was found.
        </video>
<?php else:
		//============ OLDER MSIE BROWSER:: USE EMBEDDED VIDEO OBJECT ==============
		// Use '<param name="URL" ' for WMV / '<param name="src" ' for MOV
		?>
        <object id="vidobj" classid="<?php echo hh(App::$page->getVidClassId()); ?>" 
                width ="<?php echo hh(App::$page->getVidWd()); ?>" height="<?php echo 
						hh(App::$page->getVidHt()); ?>">
            <param name="Name" value="WMP1">
            <param name="URL"  value="<?php echo hh(App::$page->getVidSrc()); ?>.wmv">
            <param name="src"  value="<?php echo hh(App::$page->getVidSrc()); ?>.wmv">
            <param name="controller" value="true"> 
            <param name="autoStart" value="<?php echo hh($_SESSION[VideoPage::SV_VID_AUTOPLAY]); ?>">
            <embed src="<?php echo hh(App::$page->getVidSrc()); ?>.wmv" 
                   width ="<?php echo hh(App::$page->getVidWd()); ?>" height="<?php echo 
							hh(App::$page->getVidHt()); ?>" 
                   controls="All" autostart="<?php echo 
							hh($_SESSION[VideoPage::SV_VID_AUTOPLAY]); ?>"></embed>
        </object>
<?php endif;
echo "\n";
if (PgLinkFactory::isCurrentPage(FilNams::PN_VIDSMY) && 
				!isset($_SESSION[SysMain::SV_JS_DISABLED])): ?>
        <form id="<?php echo hh(App::$page->getForm1()->getFormName()); ?>" name="<?php 
				echo hh(App::$page->getForm1()->getFormName()); ?>" action="<?php echo 
						uu(SAFE_RU_CURR_PAGE_URL); ?>" method="post">
			<?php App::$page->getForm1()->renderHiddenFfos1(Page::INDENT_4); ?>
            <table id="<?php echo 
					Form::FFN_VID_UPD_TBL; ?>" style="color: #000000;" class="cntr_wd98pct">
				<?php App::$page->getForm1()->renderFfos1(Page::INDENT_4); ?>
            </table>
            <button class="vidUpdBtn" name="<?php echo 
					Form::FFN_UPD_SEL_VID; ?>" id="<?php echo 
					Form::FFN_UPD_SEL_VID; ?>" value="">MODIFY selected video</button>
            <button class="vidUpdBtn" name="<?php echo 
					Form::FFN_CANCEL_UPD_VID; ?>" id="<?php echo 
					Form::FFN_CANCEL_UPD_VID; ?>" value="">CANCEL</button>
            <button class="vidUpdBtn" name="<?php echo 
					Form::FFN_DEL_SEL_VID; ?>" id="<?php echo 
					Form::FFN_DEL_SEL_VID; ?>" value="">DELETE selected video</button>
            <button class="vidUpdBtn" name="<?php echo 
					Form::FFN_DEL_ALL_VID; ?>" id="<?php echo 
					Form::FFN_DEL_ALL_VID; ?>" value="">DELETE ALL VIDEOS</button>
        </form>
<?php endif;
