<?php

/**~******************************************************************
 * Copyright (c) 2016 Voila! Video Productions
 *********************************************************************
 */

namespace AppVvp;

/**
 * Content for Services, options and pricing page
 */

?>
<div id="mainOuterBorder1" class="borderOuter">
  <div class="borderInner" style="text-align: center;">
    <h2>Services</h2>
    <p>
        Video photography of  Weddings,  Mitzvahs,  
        Birthday parties, Graduations, Retirement parties and Other Special Events
<?php //<br /><br />Fully-edited DVD with interactive menu and chapter titles    ?>
<?php //<br /><br />Conversion of your VHS tapes to DVD (with titles and editing)    ?>
        <br /><br />Your own internet webpage for viewing your videographed event
        <br /><br />Your own internet webpage with photo album
        <br /><br />Streaming Video Web design
<?php //<br /><br />Midi and audio custom background music    ?>
<?php //<br /><br />Digital editing of your home videos     ?>
        <br /><br />DVD authoring and creation
        <br /><br />DVD label and case-insert design
        <br />
    </p>
  </div>
</div>

<div id="mainOuterBorder2" class="borderOuter">
    <div class="borderInner" style="text-align: center;">
        <h2>Wedding Videography Packages</h2>
        <p>We are very flexible and will try to 
                accommodate any of your specific needs</p>
        <h4>Our packages start <strong>from $500</strong> and may include:</h4>
        <ul>
            <li>A fully-edited DVD with interactive menu, titles and chapters</li>
            <li>A recap montage with music showing the highlights of the event</li>
            <li>A family-photo montage with music</li>
            <li>High-end editing and stylish effects</li>
            <li>DVD jacket and label artwork and design</li>
        </ul>
        <p>A deposit of 1/3 the total amount is required to reserve the date and 
                time of your event</p>
    </div>
</div>
